### ISSUE TITLE
New Filter Rule Wizard is unusable on Windows

### ISSUE THREAD

**Issue by rdicroce** [eclipse-wtp-common/webtools.common#4]
Steps to reproduce:

1. Download "[Eclipse IDE for Enterprise Java and Web Developers](https://www.eclipse.org/downloads/packages/release/2024-03/r/eclipse-ide-enterprise-java-and-web-developers)"
2. Start Eclipse.
3. Click Window -> Preferences.
4. Click Validation.
5. Click "..." next to any of the validators. This brings up the "Validation Filters for X" dialog.
6. Click "Add Rule...". This brings up the "New Filter Rule Wizard" dialog.

The "New Filter Rule Wizard" dialog appears but you cannot interact with it. For some reason, the "Validation Filters for X" dialog is the top modal. If you close the "Validation Filters for X" dialog, you can then interact with the "New Filter Rule Wizard" dialog. But you can't actually create a rule. Attempting to do so causes an "Unhandled event loop exception" in the Eclipse Error Log view.

This issue was originally reported as [Bugzilla 581509](https://bugs.eclipse.org/bugs/show_bug.cgi?id=581509), but was filed against the wrong project. I am re-reporting it here in the hopes it will get fixed, and also to add more detail.

I've determined that this issue is Windows-specific. I tried 3 different Windows boxes and it was broken on all of them, but it worked fine on a Linux VM. I've also roughly pinned down the point where it broke: it works in Eclipse 2022-06 and is broken in Eclipse 2022-09.

**Comment by nitind** [comment]
I think this is addressed, now.

**Comment by rdicroce** [comment]
I downloaded the 2024-06 M2 package and upgraded it with the WTP build from May 18th. I can confirm that this problem is fixed. Thanks for the quick response!
